# Travis doesn't have a fortran build config, so we'll use c as a base and
# create our own environment
language: c
sudo: required

git:
    depth: 3
    quiet: true

env:
    matrix:
        - TYPE=MOM_solo
        - TYPE=MOM_SIS
        - TYPE=CM2M
        - TYPE=ESM2M
        - TYPE=ICCM
        - TYPE=EBM
        - TYPE=ACCESS-OM
        - TYPE=ACCESS-CM
    global:
        - FC=gfortran-4.8
        - OMPI_FC=${FC}
    
matrix:
  allow_failures:
    - env: MODEL=ACCESS-OM
    - env: MODEL=ACCESS-CM

install:
    - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install csh gcc-4.8 gfortran-4.8 libgomp1 openmpi-bin libopenmpi-dev  libnetcdf-dev  netcdf-bin

script: 
    - cd exp && ./MOM_compile.csh --type $TYPE --platform travis --use_netcdf4

# after_success:
#     - find .
#     - codecov --gcov-exec=gcov-4.8