name: CI

on: [push, pull_request]

env:
  CI: "ON" # We can detect this in the build system and other vendors implement it

jobs:
  build:
    runs-on: ubuntu-18.04 #ubuntu-latest # ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # os: ubuntu-latest 
        # [ubuntu-latest, macos-latest]
        # gcc_v: [8, 9] # Version of GFortran we want to use.
        # TYPE: [MOM_solo, MOM_SIS, CM2M, ESM2M, ICCM, EBM, ACCESS-OM, ACCESS-CM, ACCESS-OM-BGC, ACCESS-ESM]
        TYPE: [MOM_solo, MOM_SIS, ACCESS-CM, CM2M, ESM2M, ICCM, EBM]
        include:
         - TYPE: ACCESS-CM
           OASIS_ROOT: ${{ env.GITHUB_WORKSPACE }}/oasis3-mct/Linux
    env:
      # FC: gfortran-${{ matrix.gcc_v }}
      # OMPI_FC: gfortran-${{ matrix.gcc_v }}
      # GCC_V: ${{ matrix.gcc_v }}
      FC: gfortran
      OMPI_FC: gfortran

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -yqq install csh gfortran libgomp1 openmpi-bin libopenmpi-dev libnetcdf-dev libnetcdff-dev  netcdf-bin
        nf-config --flibs
        nf-config --fflags

    - name: Download OASIS
      if: startsWith(matrix.TYPE, 'ACCESS-')
      uses: actions/checkout@v2
      with: 
          repository: COSIMA/oasis3-mct

    - name: Compile OASIS
      if: startsWith(matrix.TYPE, 'ACCESS-')
      working-directory: ./oasis3-mct
      run: make ubuntu

    - name: Compile
      working-directory: ./exp
      run: |
        env
        ./MOM_compile.csh --type ${{ matrix.TYPE }} --platform travis --use_netcdf4

    # - |
    #   if [[ "$TYPE" == "ACCESS-"* ]]; then
    #     export OASIS_ROOT=$TRAVIS_BUILD_DIR/oasis3-mct/Linux
    #     git clone --depth=1 https://github.com/COSIMA/oasis3-mct.git
    #     (cd oasis3-mct && make ubuntu)
    #   fi
    # - |
    #   if [[ "$TYPE" == "ACCESS-OM" || "$TYPE" == "ACCESS-OM-BGC" ]]; then
    #     export LIBACCESSOM2_ROOT=$TRAVIS_BUILD_DIR/libaccessom2
    #     wget https://github.com/COSIMA/libaccessom2/releases/latest/download/binary_release.tar.gz
    #     tar -zxf binary_release.tar.gz
    #   fi
