name: CI

on: [push, pull_request]

env:
  CI: "ON" # We can detect this in the build system and other vendors implement it

jobs:
  build:
    runs-on: ubuntu-18.04 #ubuntu-latest # ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # os: ubuntu-latest 
        # [ubuntu-latest, macos-latest]
        # gcc_v: [8, 9] # Version of GFortran we want to use.
        TYPE: [MOM_solo, MOM_SIS, CM2M, ESM2M, ICCM, EBM, ACCESS-OM, ACCESS-CM, ACCESS-OM-BGC, ACCESS-ESM]
        # TYPE: [MOM_solo, ACCESS-CM, ACCESS-OM, MOM_SIS, CM2M, ESM2M, ICCM, EBM]
    env:
      # FC: gfortran-${{ matrix.gcc_v }}
      # OMPI_FC: gfortran-${{ matrix.gcc_v }}
      # GCC_V: ${{ matrix.gcc_v }}
      FC: gfortran8
      OMPI_FC: gfortran8

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -yqq install csh gfortran libgomp1 openmpi-bin libopenmpi-dev libnetcdf-dev libnetcdff-dev  netcdf-bin
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -yqq install gcc-8 g++-8 gfortran-8 --no-install-recommends
        nf-config --flibs
        nf-config --fflags
        gfortran8 --version

    - name: Download OASIS
      if: startsWith(matrix.TYPE, 'ACCESS-')
      uses: actions/checkout@v2
      with: 
          repository: COSIMA/oasis3-mct
          path: oasis3-mct

    - name: Compile OASIS
      if: startsWith(matrix.TYPE, 'ACCESS-')
      working-directory: ./oasis3-mct
      run: | 
        make ubuntu
        echo "oasis_dir=${{ github.workspace }}/oasis3-mct/Linux" >> $GITHUB_ENV

    - name: Download libaccessom2
      if: startsWith(matrix.TYPE, 'ACCESS-OM')
      run: | 
        wget https://github.com/COSIMA/libaccessom2/releases/latest/download/binary_release.tar.gz
        tar -zxf binary_release.tar.gz

    - name: Download libaccessom2
      if: startsWith(matrix.TYPE, 'ACCESS-OM')
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: COSIMA/libaccessom2
        workflow: CI.yml
        name: binary_release
        path: libaccessom2

    - name: Untar libaccessom2
      if: startsWith(matrix.TYPE, 'ACCESS-OM')
      working-directory: ./libaccessom2
      run: |
        tar -xvf binary_release.tar
        echo "libaccessom2_dir=${{ github.workspace }}/libaccessom2" >> $GITHUB_ENV

    - name: Compile
      working-directory: ./exp
      env: 
        OASIS_ROOT: ${{ env.oasis_dir }}
        LIBACCESSOM2_ROOT: ${{ env.libaccessom2_dir }}
      run: |
        env
        ./MOM_compile.csh --type ${{ matrix.TYPE }} --platform github --use_netcdf4

    # - |
    #   if [[ "$TYPE" == "ACCESS-OM" || "$TYPE" == "ACCESS-OM-BGC" ]]; then
    #     export LIBACCESSOM2_ROOT=$TRAVIS_BUILD_DIR/libaccessom2
    #     wget https://github.com/COSIMA/libaccessom2/releases/latest/download/binary_release.tar.gz
    #     tar -zxf binary_release.tar.gz
    #   fi
