name: CI

on: [push, pull_request]

env:
  CI: "ON" # We can detect this in the build system and other vendors implement it
  CMAKE_BUILD_PARALLEL_LEVEL: "2" # 2 cores on each GHA VM, enable parallel builds
  CTEST_OUTPUT_ON_FAILURE: "ON" # This way we don't need a flag to ctest
  CTEST_PARALLEL_LEVEL: "2"
  CTEST_TIME_TIMEOUT: "5"  # some failures hang forever
  HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ubuntu-latest # [ubuntu-latest, macos-latest]
        # gcc_v: [8, 9] # Version of GFortran we want to use.
        # TYPE: [MOM_solo, MOM_SIS, CM2M, ESM2M, ICCM, EBM, ACCESS-OM, ACCESS-CM, ACCESS-OM-BGC, ACCESS-ESM]
        TYPE: [MOM_solo, MOM_SIS]
    env:
      FC: gfortran-${{ matrix.gcc_v }}
      OMPI_FC: gfortran-${{ matrix.gcc_v }}
      GCC_V: ${{ matrix.gcc_v }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo pkg-config csh cmake
        sudo apt-get update
        sudo apt-get -yqq install libgomp1 openmpi-bin libopenmpi-dev libnetcdf-dev libnetcdff-dev  netcdf-bin
        nf-config --flibs
        nf-config --fflags

    - name: Compile
      run: |
        env
        cd exp && ./MOM_compile.csh --type $TYPE --platform travis --use_netcdf4

    # - |
    #   if [[ "$TYPE" == "ACCESS-"* ]]; then
    #     export OASIS_ROOT=$TRAVIS_BUILD_DIR/oasis3-mct/Linux
    #     git clone --depth=1 https://github.com/COSIMA/oasis3-mct.git
    #     (cd oasis3-mct && make ubuntu)
    #   fi
    # - |
    #   if [[ "$TYPE" == "ACCESS-OM" || "$TYPE" == "ACCESS-OM-BGC" ]]; then
    #     export LIBACCESSOM2_ROOT=$TRAVIS_BUILD_DIR/libaccessom2
    #     wget https://github.com/COSIMA/libaccessom2/releases/latest/download/binary_release.tar.gz
    #     tar -zxf binary_release.tar.gz
    #   fi
